dist: bionic
language: go
os: linux
go:
  - 1.14.4

services:
  - docker
addons:
  apt:
    packages:
      - docker-ce
  artifacts:
    paths:
      - artifacts
before_install:
  # the next five lines are required for certbot
  - sudo apt-get install software-properties-common -y
  - sudo add-apt-repository universe
  - sudo add-apt-repository ppa:certbot/certbot -y
  - sudo apt-get update
  - sudo apt-get install certbot -y
  # update python
  - sudo add-apt-repository ppa:deadsnakes/ppa -y
  - sudo apt-get install python3.7 && sudo apt-get install libssl-dev
  # install aws cli
  - pip install awscli --upgrade --user
  - pip install install certbot-dns-route53
install:
  # set up certbot virtualenv and activate it
  - virtualenv  --no-site-packages  -p python3.7 certbot-env
  - source certbot-env/bin/activate
  - go get -u github.com/jmckee46/deployer
  - echo "artifacts path = $DE_ARTIFACTS_PATH"
  - go run $GOPATH/src/github.com/jmckee46/deployer/travis-ci-install/main.go
  - ls -al
before_script:
  # - source certbot-env/bin/activate && tls/manage-files
  # - tls/manage-files
  - env
script:
  # - ./crank && travis-ci/deploy
after_script:
  # - travis-ci/uninstall

env:
  global:
    # - AWS_ACCESS_KEY_ID
    # - AWS_SECRET_ACCESS_KEY
    - AWS_REGION=us-west-2
    - AWS_DEFAULT_REGION=$AWS_REGION
    # the following ARTIFACTS_* environment variables are out of sort order due to dependencies on AWS_* environment variables.
    - ARTIFACTS_BUCKET=deployer.global
    - ARTIFACTS_KEY=$AWS_ACCESS_KEY_ID
    - ARTIFACTS_PATH=artifacts
    - ARTIFACTS_REGION=$AWS_REGION
    - ARTIFACTS_SECRET=$AWS_SECRET_ACCESS_KEY
    - DE_ARTIFACTS_PATH=$ARTIFACTS_PATH
    - DE_CI=true
    - DE_DOMAIN=myAppTest.com
    - DE_EMAIL=jmckee3@mac.com
    # DE_LOGGLY_TOKEN=
    - secure: "J+y9VWyrQzGaIkVwwuOsJN/EmWai7hJlJZ/TYZHZujt+l/aQkM6l6XCl/jZeiCN9hPhBGrpE4ApvrYjUGK99vqsWX+BKRJmCK5i2TBe9gxJ2wvS3jDr5l5DJTFbyX55iZLiNqRoNz1grHQCcq5TW/wvgpxA+yLTGfO/ZeGnE8H43tWe0rRObCI8Np+ROiu+QHyl3uC/IhYKVKsfMmT9Y5jsBD5teDXQ9U8PJW/34Y4oTzg5SduZwsfUnDrenHTnlkzNILhbsYmSJFy5k+Je1CYEtfPe3PATJw2RXzvGalPAmV6b+4LuNMpHHINKeH3SlF4RCXW54ShiDBZ95/j9CpfJKTz5qF8/yAm7+hhKqm8/4Sji7jUfg/yfpQVqafe9IhAziJCFndtS0Vt43brtdOy4X9UPoffoHosiwriT2GPrg08di+HFOVvui9mn2qKWVcqrtkq95LGUsSe2ixC5DefDbQUTSsVYRNjpvuhqlEzE8a+94sQ6CpmB6M7rK9/O5XCC0O1SuLX0Z6BvIzBLQYl9y9Pvrdoyioyv/8KxDTXROnJAjKiSc1mug84JaL1QwU87D12brK0nsa7cRgrwGJRgCswJsSFFZ6Q9ecYtwRpwkDog5T5LwjWTBQE+l6wJbPiWmLo2tz90wj6XuW+SfYRlKIk94TS42ZPJ3LeJdYkY="
    - DE_LOG_COLORIZATION=false
    - DE_LOG_SERIALIZATION=json-compact
    # DE_MIGRATIONS_PGPASSWORD=
    - DE_GIT_SHA=$TRAVIS_COMMIT
    - DE_GLOBAL_BUCKET=$ARTIFACTS_BUCKET
    - DE_VPC_CIDR_BASE=192.168.0
    - DE_SUBNET_CIDR_BLOCKS=192.168.0.0/24,192.168.1.0/24,192.168.2.0/24
    - GO111MODULE=on
    - HOSTED_ZONE_ID=/hostedzone/Z015966636UQ1OFVQD7CA
    - PYTHONWARNINGS="ignore"
    # the remaining env-vars are order dependent
    - DE_GIT_BRANCH=$(echo $TRAVIS_BRANCH | tr '[:upper:]' '[:lower:]')
    - DE_GIT_BRANCH_HASH=$(echo -n $DE_GIT_BRANCH | shasum -a 256)
    - DE_STACK_NAME=${DE_GIT_BRANCH:0:8}-${DE_GIT_BRANCH_HASH:0:4}
    - DE_LOAD_BALANCER_HOSTNAME=$DE_STACK_NAME.$DE_DOMAIN
    # - DE_STACK_BUCKET=deployer.stack.$D_STACK_NAME

  

