FROM postgres:9.6.3-alpine
MAINTAINER John McKee <john@subledger.com>

ENV DOCKER_IMAGE=images-to-deploy/postgres

LABEL com.subledger.deployer.push="true"
LABEL com.subledger.deployer.postgres="true"
